# Generated by Django 4.2.27 on 2026-01-13 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('SIEM', 'Security Information and Event Management'), ('EDR', 'Endpoint Detection and Response'), ('AV', 'Antivirus'), ('FIREWALL', 'Firewall'), ('IDS', 'Intrusion Detection System'), ('CUSTOM', 'Custom Source')], max_length=20)),
                ('source_id', models.CharField(help_text='Unique identifier for this source', max_length=50, unique=True)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key'), ('oauth2', 'OAuth2')], default='bearer', max_length=50)),
                ('polling_enabled', models.BooleanField(default=True)),
                ('polling_interval', models.IntegerField(default=60, help_text='Polling interval in seconds')),
                ('last_poll_time', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('webhook_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Source',
                'verbose_name_plural': 'Alert Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestion_type', models.CharField(choices=[('poll', 'Polling'), ('webhook', 'Webhook')], max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial Success'), ('error', 'Error')], default='started', max_length=20)),
                ('alerts_received', models.IntegerField(default=0)),
                ('alerts_sent_to_kafka', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='alerts.alertsource')),
            ],
            options={
                'verbose_name': 'Ingestion Log',
                'verbose_name_plural': 'Ingestion Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
